load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "configuration_manager",
    srcs = ['configuration_manager.cc'],
    hdrs = ['configuration_manager.h'],
    visibility = ["//visibility:public"]
)

cc_library(
    name = "configuration",
    srcs = ['configuration.cc'],
    hdrs = ['configuration.h'],
    visibility = ["//visibility:public"]
)