load("@rules_cc//cc:defs.bzl", "cc_library")
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "version",
    hdrs = [
        "version.h"
    ],
    includes=[
        "aipilot/services/dfg_avm_calib/include",
    ],
)