INCLUDE_DIRECTORIES(
${AIPLORE_ROOT}/third_party/json_3.10.5/include
${AIPLORE_ROOT}/common/tda4/dds/include
${AIPLORE_ROOT}/common/tda4/apa_interface_1.0.0/include
${AIPLORE_ROOT}/common/tda4/app_utils_minicv_2.0.0/include
${AIPLORE_ROOT}/common/tda4/apa_common_1.0.0/include
${AIPLORE_ROOT}/common/tda4/shared_env_1.0.0/include
${AIPLORE_ROOT}/common/tda4/common_2.0.1/include
${AIPLORE_ROOT}/common/tda4/gtctimer_0.1.2/include
${AIPLORE_ROOT}/common/tda4/bev_inference/include
${AIPLORE_ROOT}/common/tda4/diag_agent_1.0.11/include
${AIPLORE_ROOT}/common/tda4/apa_transparent/include
${AIPLORE_ROOT}/third_party/glm-0.9.9.8/include
${AIPLORE_ROOT}/third_party/msgpack-c_3.1.1/include
${AIPLORE_ROOT}/third_party/tda4/protobuf_3.12.3/include
${AIPLORE_ROOT}/third_party/tda4/gflags_2.2.2/include
${AIPLORE_ROOT}/third_party/tda4/glog_0.3.5/include
${AIPLORE_ROOT}/third_party/tda4/libflow_1.0.0/include
${AIPLORE_ROOT}/third_party/tda4/ceres_1.14.x/include
${AIPLORE_ROOT}/third_party/eigen_3.4.0/include
${AIPLORE_ROOT}/third_party/tda4/nanomsg_1.1.5/include
${AIPLORE_ROOT}/third_party/tda4/yaml-cpp-0.7.0/include
${AIPLORE_ROOT}/third_party/tda4/dlt_2.18.8/include
${AIPLORE_ROOT}/third_party/tda4/osqp_0.5.0/include
${AIPLORE_ROOT}/third_party/tda4/assimp_5.2.2/include
${TDA4_SYS_ROOT}/usr/include/opencv4
)

LINK_DIRECTORIES(
${AIPLORE_ROOT}/common/tda4/dds/lib
${AIPLORE_ROOT}/common/tda4/app_utils_minicv_2.0.0/lib
${AIPLORE_ROOT}/common/tda4/apa_common_1.0.0/lib
${AIPLORE_ROOT}/common/tda4/shared_env_1.0.0/lib
${AIPLORE_ROOT}/common/tda4/common_2.0.1/lib
${AIPLORE_ROOT}/common/tda4/gtctimer_0.1.2/lib
${AIPLORE_ROOT}/common/tda4/bev_inference/lib
${AIPLORE_ROOT}/common/tda4/diag_agent_1.0.11/lib
${AIPLORE_ROOT}/common/tda4/apa_transparent/lib
${AIPLORE_ROOT}/third_party/tda4/protobuf_3.12.3/lib
${AIPLORE_ROOT}/third_party/tda4/gflags_2.2.2/lib
${AIPLORE_ROOT}/third_party/tda4/glog_0.3.5/lib
${AIPLORE_ROOT}/third_party/tda4/libflow_1.0.0/lib
${AIPLORE_ROOT}/third_party/tda4/ceres_1.14.x/lib
${AIPLORE_ROOT}/third_party/tda4/nanomsg_1.1.5/lib
${AIPLORE_ROOT}/third_party/tda4/yaml-cpp-0.7.0/lib
${AIPLORE_ROOT}/third_party/tda4/dlt_2.18.8/lib
${AIPLORE_ROOT}/third_party/tda4/osqp_0.5.0/lib
${AIPLORE_ROOT}/third_party/tda4/assimp_5.2.2/lib
${TDA4_SYS_ROOT}/usr/lib
)

