INCLUDE_DIRECTORIES(
${AIPLORE_ROOT}/common/linux/common_2.0.1/include/
${AIPLORE_ROOT}/common/linux/common_2.0.1/include/common
${AIPLORE_ROOT}/common/linux/dds/include
${AIPLORE_ROOT}/common/linux/apa_common_1.0.0/include
${AIPLORE_ROOT}/common/linux/apa_interface_1.0.0/include
${AIPLORE_ROOT}/common/linux/apa_cnn_1.0.3/include
${AIPLORE_ROOT}/common/linux/apa_log_reader_1.2.0/include
${AIPLORE_ROOT}/common/linux/gtctimer_0.1.2/include
${AIPLORE_ROOT}/common/linux/diag_agent_1.0.11/include
${AIPLORE_ROOT}/third_party/glm-0.9.9.8/include
${AIPLORE_ROOT}/third_party/linux/nanomsg_1.1.5/include
${AIPLORE_ROOT}/third_party/linux/caffe_1.0.0-rc.27.pb_3.12.3/include
${AIPLORE_ROOT}/third_party/linux/openblas_0.3.5-rc.3/include
${AIPLORE_ROOT}/third_party/eigen_3.4.0/include
${AIPLORE_ROOT}/third_party/linux/libflow_1.0.0/include
${AIPLORE_ROOT}/third_party/json_3.10.5/include
${AIPLORE_ROOT}/third_party/linux/boost_1.68.0/include
${AIPLORE_ROOT}/third_party/msgpack-c_3.1.1/include
${AIPLORE_ROOT}/third_party/linux/glog_0.3.5/include
${AIPLORE_ROOT}/third_party/linux/gtest_1.8.1/include
${AIPLORE_ROOT}/third_party/linux/protobuf_3.12.3/include
${AIPLORE_ROOT}/third_party/linux/gflags_2.2.2/include
${AIPLORE_ROOT}/third_party/linux/opencv_3.4.8/include
${AIPLORE_ROOT}/third_party/linux/ceres_1.14.x/include
${AIPLORE_ROOT}/third_party/linux/yaml-cpp-0.7.0/include
${AIPLORE_ROOT}/third_party/linux/dlt_2.18.8/include
${AIPLORE_ROOT}/third_party/linux/osqp_0.5.0/include
${AIPLORE_ROOT}/third_party/linux/Pangolin-0.8/include
${AIPLORE_ROOT}/third_party/linux/assimp_5.2.2/include
)


LINK_DIRECTORIES(
${AIPLORE_ROOT}/common/linux/common_2.0.1/lib
${AIPLORE_ROOT}/common/linux/dds/lib
${AIPLORE_ROOT}/common/linux/apa_common_1.0.0/lib
${AIPLORE_ROOT}/common/linux/apa_cnn_1.0.3/lib
${AIPLORE_ROOT}/common/linux/apa_log_reader_1.2.0/lib
${AIPLORE_ROOT}/common/linux/gtctimer_0.1.2/lib
${AIPLORE_ROOT}/common/linux/diag_agent_1.0.11/lib
${AIPLORE_ROOT}/third_party/linux/nanomsg_1.1.5/lib
${AIPLORE_ROOT}/third_party/linux/caffe_1.0.0-rc.27.pb_3.12.3/lib
${AIPLORE_ROOT}/third_party/linux/openblas_0.3.5-rc.3/lib
${AIPLORE_ROOT}/third_party/linux/libflow_1.0.0/lib
${AIPLORE_ROOT}/third_party/linux/boost_1.68.0/lib
${AIPLORE_ROOT}/third_party/linux/glog_0.3.5/lib
${AIPLORE_ROOT}/third_party/linux/gtest_1.8.1/lib
${AIPLORE_ROOT}/third_party/linux/protobuf_3.12.3/lib
${AIPLORE_ROOT}/third_party/linux/gflags_2.2.2/lib
${AIPLORE_ROOT}/third_party/linux/opencv_3.4.8/lib
${AIPLORE_ROOT}/third_party/linux/opencv_3.4.8/3rdparty/lib
${AIPLORE_ROOT}/third_party/linux/opencv_3.4.8/share/OpenCV/3rdparty/lib
${AIPLORE_ROOT}/third_party/linux/ceres_1.14.x/lib
${AIPLORE_ROOT}/third_party/linux/yaml-cpp-0.7.0/lib
${AIPLORE_ROOT}/third_party/linux/dlt_2.18.8/lib
${AIPLORE_ROOT}/third_party/linux/osqp_0.5.0/lib
${AIPLORE_ROOT}/third_party/linux/assimp_5.2.2/lib
${AIPLORE_ROOT}/third_party/linux/Pangolin-0.8/lib
)

