INCLUDE_DIRECTORIES(
${AIPLORE_ROOT}/third_party/json_3.10.5/include
${AIPLORE_ROOT}/common/J3/dds/include
${AIPLORE_ROOT}/common/J3/common_2.0.1/include
${AIPLORE_ROOT}/common/J3/gtctimer_0.1.2/include
${AIPLORE_ROOT}/third_party/glm-0.9.9.8/include
${AIPLORE_ROOT}/third_party/msgpack-c_3.1.1/include
${AIPLORE_ROOT}/third_party/J3/protobuf_3.12.3/include
${AIPLORE_ROOT}/third_party/J3/gflags_2.2.2/include
${AIPLORE_ROOT}/third_party/J3/libflow_1.0.0/include
${AIPLORE_ROOT}/third_party/J3/glog_0.3.5/include
${AIPLORE_ROOT}/third_party/eigen_3.3.4/include
${AIPLORE_ROOT}/third_party/J3/nanomsg_1.1.5/include
${AIPLORE_ROOT}/third_party/J3/yaml-cpp-0.7.0/include
${AIPLORE_ROOT}/third_party/J3/dlt_2.18.8/include
${AIPLORE_ROOT}/third_party/J3/osqp_0.5.0/include
${AIPLORE_ROOT}/common/J3/extraflow/include
${AIPLORE_ROOT}/common/J3/diag_agent_1.0.11/include
${AIPLORE_ROOT}/third_party/J3/opencv_4.1.0/include/opencv4
${AIPLORE_ROOT}/common/J3/obj_cnn/include
#${J3_SYS_ROOT}/include
#${J3_SYS_ROOT}/include/opencv3
)

LINK_DIRECTORIES(
${AIPLORE_ROOT}/common/J3/dds/lib
${AIPLORE_ROOT}/common/J3/common_2.0.1/lib
${AIPLORE_ROOT}/common/J3/gtctimer_0.1.2/lib
${AIPLORE_ROOT}/third_party/J3/protobuf_3.12.3/lib
${AIPLORE_ROOT}/third_party/J3/gflags_2.2.2/lib
${AIPLORE_ROOT}/third_party/J3/libflow_1.0.0/lib
${AIPLORE_ROOT}/third_party/J3/glog_0.3.5/lib
${AIPLORE_ROOT}/third_party/J3/nanomsg_1.1.5/lib
${AIPLORE_ROOT}/third_party/J3/yaml-cpp-0.7.0/lib
${AIPLORE_ROOT}/third_party/J3/dlt_2.18.8/lib
${AIPLORE_ROOT}/third_party/J3/osqp_0.5.0/lib
${AIPLORE_ROOT}/common/J3/extraflow/lib
${AIPLORE_ROOT}/common/J3/diag_agent_1.0.11/lib
${AIPLORE_ROOT}/third_party/J3/opencv_4.1.0/lib
${AIPLORE_ROOT}/common/J3/obj_cnn/lib
)

