load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "bev_inf",
    hdrs = glob([
        "usr/include/**/*.h",
        "usr/include/processor_sdk/ivision/**/*.h",
        "usr/include/processor_sdk/tidl_j7_02_00_00_07/ti_dl/inc/**/*.h",
        "usr/include/processor_sdk/tiovx/include/**/*.h",
        "usr/include/processor_sdk/tiovx/kernels/include/**/*.h",
        "usr/include/processor_sdk/tiovx/kernels_j7/include/**/*.h",
        "usr/include/processor_sdk/tiovx/utils/include/**/*.h",
        "usr/include/processor_sdk/vision_apps/**/*.h",
        "usr/include/processor_sdk/vision_apps/apps/basic_demos/app_tirtos/common/**/*.h",
        "usr/include/processor_sdk/vision_apps/apps/basic_demos/app_tirtos/tirtos_qnx/**/*.h",
        "usr/include/processor_sdk/vision_apps/kernels/img_proc/include/**/*.h",
        "usr/include/processor_sdk/vision_apps/utils/opengl/include/**/*.h",
        "usr/include/processor_sdk/vision_apps/apps/basic_demos/app_tirtos/tirtos_linux/mpu1/**/*.h",
        "usr/include/processor_sdk/vision_apps/utils/mem/include/**/*.h",
    ]),
    srcs = glob([
                 "usr/lib/libtivision_apps.so*",
                 "usr/lib/libGLESv2.so*",
                 "usr/lib/libEGL.so*",
                 "usr/lib/libdl.so*",
                 "usr/lib/libgbm.so*",
                 "usr/lib/libdrm.so*",
                 "usr/lib/libxml2.so*",
                 "usr/lib/libm.so*",
                 "usr/lib/libti_rpmsg_char.so*",
                ]),
    includes = [
        "usr/include",
        "usr/include/processor_sdk/ivision",
        "usr/include/processor_sdk/tidl_j7_02_00_00_07/ti_dl/inc",
        "usr/include/processor_sdk/tiovx/include",
        "usr/include/processor_sdk/tiovx/kernels/include",
        "usr/include/processor_sdk/tiovx/kernels_j7/include",
        "usr/include/processor_sdk/tiovx/utils/include",
        "usr/include/processor_sdk/vision_apps",
        "usr/include/processor_sdk/vision_apps/apps/basic_demos/app_tirtos/common",
        "usr/include/processor_sdk/vision_apps/apps/basic_demos/app_tirtos/tirtos_qnx",
        "usr/include/processor_sdk/vision_apps/kernels/img_proc/include",
        "usr/include/processor_sdk/vision_apps/utils/opengl/include",
        "usr/include/processor_sdk/vision_apps/apps/basic_demos/app_tirtos/tirtos_linux/mpu1",
        "usr/include/processor_sdk/vision_apps/utils/mem/include",
    ],
    linkstatic = 0,               
    visibility = ["//visibility:public"],
)
